### ISSUE TITLE
Mail-Enaled Contact - pound sign (#)

### ISSUE THREAD

**Issue by adamdrayer** [timmcmic/DLConversionV2#8] opened 2021-09-21 19:29 UTC
The fix for migrating DLs with "#" works well for the groups but it fails when you use -EnableHybridMailFlow. The issue persists with the mail-enabled contact object.  

Note the attached error log.  The mail-enabled contact object it creates has a "\\#" in the actual DN, but when it searches for the object, it searches for a DN that doesn't contain the "\\" and fails.

![image-dlmigrate](https://user-images.githubusercontent.com/48683398/134235160-5d8481ff-35fe-4550-ac6b-70a72ac490a6.png)
me

**Comment by adamdrayer** [comment] 2021-09-21 19:43
Update:  This fails without -EnableHybridMailFlow also.  The group is migrated but the script still errors out when trying to locate the mail-enabled contact object.  The object is created with the unmodified value from the XML which contains a "\\"

Side note: we are running this in Powershell ISE, and when it fails, it kills the ISE window.  Is there any way to avoid that?

Thanks so much for this script.  It is going to be a big help.

**Comment by timmcmic** [comment] 2021-09-21 20:01
Would you send me a sample DL name and SMTP address so I can test?  I want to make sure I'm reproducing the same scenario.

**Comment by dickfrazier** [comment] 2021-09-21 20:08
This is very similar to the issue I put up on the V1 version.  Is this version still in development? V1 is working for me unless I use a pound sign.

**Comment by timmcmic** [comment] 2021-09-21 20:09
V1 is not currently in development anymore - at least I'm not maintaining it.

Tim

**Comment by timmcmic** [comment] 2021-09-21 20:17
It exits because the script explicitly calls EXIT on failure.

**Comment by adamdrayer** [comment] 2021-09-21 20:35
Thanks for the fast response. The DL name and smtp are:
DL Name "#O365 DL Move Test 6"
SMTP="#o365dlmovetest6@contoso.com"

**Comment by timmcmic** [comment] 2021-09-22 03:38
Adam...thanks for the feedback.

Update to the latest module version and give it a go.  I think I have it worked out.

I just tried group #Pound#Pound#@contoso.com and it worked.

I had to make a few updates (they're in the multi-branch btw since that's where I was already working).

The get-adobject code already has two paths - search via mail or dn.  The get routing contact attempted to build a DN.  I nulled that code out and had it build the contacts SMTP address.  So now it invokes the get using the mail address.

The other thing I discovered is that get-acl would fail with the escape characters in the DN - especially if it was a first or last character.  This appears to be a known issue in windows 2019 and some builds of windows 10.  I went ahead and used a workaround to specify a full path for the AD providers - and when passed into the invoke-command gives us the ACLs so we can test for send as.

In brief testing this evening it looked good with these special characters.

**Comment by adamdrayer** [comment] 2021-09-22 04:08
That makes sense to use mail instead of dn in this case.  Thank you for working on this so fast!  I will test it tomorrow with my colleague and get back to you.  It may take 24 hours for a confirmation that it works.

We found another peculiar behavior and I will open a separate issue on it but I appreciate all the work you have done on this issue.  We can work around this new issue if you cannot get to it.  Thanks so much again.

**Comment by timmcmic** [comment] 2021-09-23 17:48
@adamdrayer  any comment - if all looks good for you to i'll close this issue.

**Comment by adamdrayer** [comment] 2021-09-23 17:49
Sorry we had to delay our testing until 10am ET tomorrow.

**Comment by adamdrayer** [comment] 2021-09-24 15:14
This is fixed now, thanks!  Please feel free to close

**Closed** 2021-09-27 17:35 UTC
