### ISSUE TITLE
6th DL to migrate fails

### ISSUE THREAD

**Issue by adamdrayer** [timmcmic/DLConversionV2#17] opened 2021-09-27 21:57 UTC
Tim, sorry again to open so many issues, but we just tried to migrate 6 lists and the 6th never started.  I tracked it down to this code:

---------------------------
       if ($global:threadNumber -eq 1)
       {
           out-logfile -string "This is the master thread responsible for triggering operations."
           out-logfile -string "Search status directory and count files - if file count = number of threads - 1 thread 1 can proceed."

           #Do the following until the count of the files in the directory = number of threads - 1.

           do 
           {
               start-sleepProgress -sleepString "Other threads are pending.  Sleep 5 seconds." -sleepSeconds 5
           } until ((get-statusFileCount) -eq ($totalThreadCount - 1))
---------------------------------

Note the UNTIL clause

The first few times this code is executed Get-StatusFileCount returns "5" and $TotalThreadCount returns "5".  Then eventually the status files for threads 2-5 are cleaned up and Get-StatusFileCount returns 1, so the until condition is never satisfied.

I did some digging and here is what I found...

I believe the status file for thread #1 (ThreadOneStatus.txt) is supposed to be cleaned up.  But in the code where new-office365dl is executed (Github lines 3038-3062, DLConversionV2.psm1), you have it looping because the command fails the first few times.  When it fails, it uses out-logFile.

Code:

out-logfile "Attempting to create the DL in Office 365."

    $stopLoop = $FALSE
    [int]$loopCounter = 0

    do {
        try {
            new-office365dl -originalDLConfiguration $originalDLConfiguration -grouptypeoverride $groupTypeOverride -errorAction STOP

            #If we made it this far then the group was created.

            $stopLoop=$TRUE
        }
        catch {
            if ($loopCounter -gt 10)
            {
                out-logFile -string $_ -isError:$TRUE 
            }
            else 
            {
                out-logfile -string "Unable to create the distribution list on attempt.  Retry"
                $loopCounter=$loopCounter+1
            }
        }
    } while ($stopLoop -eq $FALSE)

Out-Logfile has code that re-creates the status file if there is a terminating error.  The inability to create the O365 DL is a terminating error and so ThreadOneStatus.txt is created from the out-logfile function and never cleaned up.

Code from Out-LogFile:
     #If the output to the log is terminating exception - throw the same string.

        if ($isError -eq $TRUE)
        {
            if ($global:ThreadNumber -gt 0)
            {
                out-statusFile -threadNumber $global:ThreadNumber
            }

            write-error $logString
            disable-allPowerShellSessions

            if ($isAudit -eq $FALSE)
            {
                Start-ArchiveFiles -isSuccess:$FALSE -logFolderPath $logFolderPath
            }
            exit
        }
    }

If ThreadOneStatus.txt were not created during this call to out-logfile, or cleaned up afterwards then there would be 4 status files in the folder and the UNTIL condition might be satisfied

**Comment by timmcmic** [comment] 2021-09-28 01:03
First - never apologize.  This is great.  I thought maybe I was going crazy.  I observed one off in the lab but could not reliably reproduce.  This makes total sense.

So the code executes in the out file to create the status file - so that if any of the threads exit the status file exists so other threads proceed.  Since there's really not a way to share a global thread counter between each status file.  

If thread one exits and abends - then this is going to happen.  I'll need to sit down and think about this again - but that would explain it.  The failure of thread one write out the status file and then the rest of the threads pick it up.

Let me look at it.

**Comment by timmcmic** [comment] 2021-09-28 02:39
I think I found the issue as you highlighted - kinda.  So I found a thread one example where it's failing.  A few builds ago I put retry code in to the majority of functions that kept failing with transient errors due to timing.  This is all the do while stoploop= that you see in the code.  Instead of proactively sleeping inbetween calls - go ahead and make them / capture the exception / and bail if they fail X times.  This made sleeps only necessary when they were necessary - and provided an out if it was actually a hard failure that time was not going to fix.

In the log I was looking at you can see similar to what you were pointing out.  In this case it was trying to update the SMTP addresses of the object - and when it tried it got a duel write error.  The out code was excuted in the catch statement - and triggered the out file generation.  The issue is that the exit never executed - it just went back and looped around and retried the operation -> as it should under this error handling.

I went through and found all the functions where I put in the do / while logic to avoid sleeps and transient issues.  I then went in to those functions and removed the -isError;$TRUE from each of them.  So now if a function call in the do is executed the exception will still be logged -> but no status file will be generated.  The status file will only ever be generated if it hits the max retry count in the do while -> at which time it is a hard failure and it should generate.  Then that thread will exit hard with an unrecoverable failure and no further processing for that one will happen.

I'll stress test this tomorrow and then make sure that it does not introduce any regressions that I can see.

**Comment by adamdrayer** [comment] 2021-09-28 02:43
I want to thank you so much for all your work.  I had a feeling the "isError:$TRUE" might be triggering the permanent failure and creating the status file in this "catch" loop but I already felt bad digging into your code as much as I did.

This script will be a huge benefit to my organization and your time and effort in developing is amazing.  If you want a LinkedIn testimonial or anything like that, please let me know.

Thank you for being so responsive and I hope I was able to help a little with my research so the burden was eased a little for you.

Sincerely,

Adam

**Comment by timmcmic** [comment] 2021-09-28 11:42
That's the point of gitHub - review the code and make comments - clone the repository and your own goodies.

**Comment by timmcmic** [comment] 2021-09-28 21:24
@adamdrayer - here's the latest status.

I finally worked out what is happening here.  It's somewhat convoluted.

So - a while back I took a code change to deal with retriable errors.  For example, when you delete a distribution list and then rapidly try to recreate it -> it would often error due to service cache.  You can see failures also like the dual write failures between azure ad and exchange.  Essentially there are things that originally would fail and bail the entire migration -> and now we sleep and retry.  

This is accomplished by using the do -> while with stoploop.

So what's happening here.

Enter do / while.
Attempt for example new-o365DL.
Enter create new o365DL function.
Encounter error creating the dl.
Call out-file with isError:$TRUE
Enter out-file isError section.
---Write status file.
---Write-error is called with the default error preference continue.
-----This throws a new error.
This new error is caught by the do while in the main function.
The new DL attempt is made again.

So you're analysis was spot on.  The status file go created, then the function came back and did what it was supposed to do.  The script continues - but the status file remains.

The fix at least NOW is pretty simple.  

Enter do / while.
Attempt for example new-o365DL.
Enter create new o365DL function.
Encounter error creating the dl.
Call out-file with isError:$TRUE
Enter out-file isError section.
---Write-error is called with the default error preference continue.
-----This throws a new error.
---Write status file.
This new error is caught by the do while in the main function.
The new DL attempt is made again.

The status file is moved outside of write-error.  In this instance - we're totally abusing write-error here using it to essentially rethrow the original error already handled in the try catch.  Since the functions that all call up to this use errorAction STOP -> the do while catch fires and grabs it.  

We'll definitely need to find a better way to do this.

In the event of standard errors - the STOP does not originate through out-file and since error action preference is continue write-error just shows it on the screen and then it continues on creating the status file.

The latest build is stress testing now.  I'll update here when it's published.

**Comment by timmcmic** [comment] 2021-09-28 23:41
This tested well - version 2.4.7 released to powershell gallery.

**Comment by adamdrayer** [comment] 2021-09-29 13:15
Will test today and let you know.  Thanks so much!

**Comment by timmcmic** [comment] 2021-10-04 23:42
Closing

**Closed by timmcmic** 2021-10-04 23:42 UTC

**Comment by adamdrayer** [comment] 2021-10-05 15:41
Sorry for not getting back to you on this.  This worked for us.
